version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - food_namdo
      - image_search_recommend

  frontend:
    build: ./frontend
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - /usr/src/app/node_modules
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - food_namdo
    stdin_open: true
    restart: always

  food_namdo:
    build: ./backend/FoodNamdo
    ports:
      - "8080:8080"
    depends_on:
      - image_search_recommend
    env_file: .env
    restart: always

  image_search_recommend:
    build: ./backend/imageSearchRecommend
    volumes:
      - ./backend/imageSearchRecommend:/usr/src/app
    ports:
      - "8000:8000"
    env_file: .env
    restart: always