from enum import Enum

class Column(Enum):
    distance = "distance"
    rstr_num = "rstr_num"
    rstr_region = "rstr_region"
    rstr_permission = "rstr_permission"
    rstr_name = "rstr_name"
    rstr_address = "rstr_address"
    rstr_la = "rstr_la"
    rstr_lo = "rstr_lo"
    rstr_tel = "rstr_tel"
    rstr_intro = "rstr_intro"
    rstr_naver_rating = "rstr_naver_rating"
    rstr_review_rating = "rstr_review_rating"
    example = "example"
    relax = "relax"
    rstr_favorite_count = "rstr_favorite_count"
    rstr_parking = "rstr_parking"
    rstr_play = "rstr_play"
    rstr_pet = "rstr_pet"
    rstr_closed = "rstr_closed"
    rstr_business_hour = "rstr_business_hour"
    rstr_delivery = "rstr_delivery"